from __future__ import annotations

from app.document.semantic_ai.models import SemanticConcept


BUILTIN_CONCEPTS: tuple[SemanticConcept, ...] = (
    SemanticConcept(
        "procurement.ata_number",
        "Número da Ata",
        "text",
        (
            "número da ata de registro de preços",
            "ata de registro de preços nº",
            "nº da arp",
            "numero da arp",
            "ata nº",
        ),
        0.97,
        "inline",
        ("arp", "ata"),
    ),
    SemanticConcept(
        "procurement.managing_agency",
        "Órgão gerenciador",
        "text",
        (
            "órgão gerenciador",
            "orgao gerenciador da ata",
            "gerenciada pela secretaria",
            "unidade gerenciadora da arp",
        ),
        0.94,
        "inline",
    ),
    SemanticConcept(
        "organization.acronym",
        "Sigla do órgão",
        "text",
        ("sigla do órgão", "sigla da secretaria", "abreviação do órgão"),
        0.88,
        "inline",
    ),
    SemanticConcept(
        "process.number",
        "Número do processo",
        "text",
        ("número do processo", "processo nº", "nº do processo administrativo"),
        0.96,
        "inline",
    ),
    SemanticConcept(
        "contract.number",
        "Número do contrato",
        "text",
        ("número do contrato", "contrato nº", "nº do contrato"),
        0.94,
        "inline",
    ),
    SemanticConcept(
        "person.name",
        "Nome",
        "text",
        ("nome completo", "nome do responsável", "nome do signatário", "servidor responsável"),
        0.91,
        "inline",
    ),
    SemanticConcept(
        "person.role",
        "Cargo / função",
        "text",
        ("cargo", "função", "funcao", "cargo do responsável", "função do signatário"),
        0.88,
        "inline",
    ),
    SemanticConcept(
        "person.registration",
        "Matrícula",
        "text",
        ("matrícula", "matricula do servidor", "registro funcional"),
        0.94,
        "inline",
    ),
    SemanticConcept(
        "organization.unit",
        "Unidade requisitante",
        "text",
        (
            "unidade requisitante",
            "unidade demandante",
            "setor requisitante",
            "área requisitante",
            "area demandante",
        ),
        0.90,
        "inline",
    ),
    SemanticConcept(
        "procurement.object",
        "Objeto",
        "multiline",
        ("objeto da contratação", "objeto", "descrição do objeto", "descricao da contratação"),
        0.88,
        "paragraph",
    ),
    SemanticConcept(
        "justification.general",
        "Justificativa",
        "multiline",
        (
            "justificativa da contratação",
            "justificativa de vantajosidade",
            "fundamentação da contratação",
            "motivação da contratação",
            "razões da contratação",
        ),
        0.83,
        "paragraph",
    ),
    SemanticConcept(
        "justification.celerity",
        "Celeridade do Processo",
        "multiline",
        ("celeridade do processo", "agilidade do processo", "redução de prazos"),
        0.78,
        "paragraph",
    ),
    SemanticConcept(
        "justification.economy",
        "Economicidade",
        "multiline",
        ("economicidade", "vantagem econômica", "preços compatíveis", "economia"),
        0.78,
        "paragraph",
    ),
    SemanticConcept(
        "justification.efficiency",
        "Eficiência Administrativa",
        "multiline",
        ("eficiência administrativa", "otimização de recursos", "eficiencia"),
        0.78,
        "paragraph",
    ),
    SemanticConcept(
        "justification.legal_security",
        "Segurança Jurídica",
        "multiline",
        ("segurança jurídica", "legalidade", "confiabilidade jurídica"),
        0.78,
        "paragraph",
    ),
    SemanticConcept(
        "justification.continuity",
        "Atendimento Contínuo e Essencial",
        "multiline",
        ("atendimento contínuo", "serviço essencial", "continuidade das atividades"),
        0.78,
        "paragraph",
    ),
    SemanticConcept(
        "justification.conclusion",
        "Conclusão da justificativa",
        "multiline",
        ("diante do exposto", "conclui-se", "ante o exposto", "solução mais eficiente"),
        0.72,
        "paragraph",
    ),
    SemanticConcept(
        "procurement.items",
        "Materiais / itens",
        "repeatable_list",
        (
            "materiais contemplados",
            "itens da contratação",
            "lista de materiais",
            "materiais de expediente contemplando",
            "itens solicitados",
        ),
        0.82,
        "list",
    ),
    SemanticConcept(
        "date.generic",
        "Data",
        "date",
        ("data prevista", "data da assinatura", "previsão de entrega", "data de início"),
        0.90,
        "inline",
    ),
    SemanticConcept(
        "contact.email",
        "E-mail",
        "email",
        ("e-mail", "email", "correio eletrônico"),
        0.98,
        "inline",
    ),
    SemanticConcept(
        "contact.phone",
        "Telefone",
        "phone",
        ("telefone", "celular", "fone", "contato telefônico"),
        0.97,
        "inline",
    ),
)
